c_compiler: gcc
c_compiler_version: 9
cxx_compiler: gxx
cxx_compiler_version: 9
ignore_build_only_deps:
- numpy
- python
numpy: '1.18'
tbb: '2021.1.1'
python:
- 3.7
#- 3.8
boost_cpp: '1.72'
pin_run_as_build:
  boost-cpp:
    max_pin: x.x.x
