name: Reusable build action
on:
  workflow_call:
    inputs:
      cuda_compiler_version:
        type: string
        default: None

    outputs:
      cache-suffix:
        value: ${{ jobs.build.outputs.cache-suffix }}

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      cuda_compiler_version: ${{ inputs.cuda_compiler_version }}
      PREFIX: distr
      CONDA_ENV: omnisci-dev

    outputs:
      cache-suffix: ${{ env.DATE }}

    steps:
      - uses: actions/checkout@v3

      - name: Free space
        run: |
          sudo rm -rf /usr/local/lib/android/sdk /opt/hostedtoolcache /usr/share/swift /opt/az
          sudo apt-get purge -y gcc

      - name: Set env context
        run: |
          echo CONDA_PATH=$CONDA >>$GITHUB_ENV
          echo RUN_STAMP=${{ runner.os }}-${{ (env.cuda_compiler_version != 'None') && format('cuda{0}', env.cuda_compiler_version) || 'cpu' }} >>$GITHUB_ENV
          echo CONDA_ENV_PATH=$CONDA/envs/${{ env.CONDA_ENV }} >>$GITHUB_ENV
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo ${{ hashFiles('omniscidb/scripts/mapd-deps-conda-dev-env.yml') }}
          echo ${{ hashFiles('CMakeLists.txt') }}

      - name: Restore Conda env cache
        id: conda-cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.CONDA_ENV_PATH }}
          key: ${{ env.RUN_STAMP }}-conda-${{ hashFiles('omniscidb/scripts/mapd-deps-conda-dev-env.yml') }}-${{ env.DATE }}
          restore-keys: |
            ${{ env.RUN_STAMP }}-conda-${{ hashFiles('omniscidb/scripts/mapd-deps-conda-dev-env.yml') }}-

      - name: Update Conda env
        if: steps.conda-cache.cache-hit != 'true'
        run: |
          conda update conda
          conda env update -f omniscidb/scripts/mapd-deps-conda-dev-env.yml

      - name: Install cudatoolkit-dev
        if: env.cuda_compiler_version != 'None'
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb
          sudo dpkg -i cuda-keyring_1.0-1_all.deb
          sudo apt-get update
          sudo apt-get install cuda-nvcc-${{ env.cuda_compiler_version }}
          conda install -n ${{ env.CONDA_ENV }} -c conda-forge arrow-cpp-proc=4.0.0=cuda

      - name: Restore Maven cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
          key: ${{ env.RUN_STAMP }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ env.RUN_STAMP }}-maven-

      - name: Build
        env:
          CPU_COUNT: 2
          RUN_TESTS: 1
        run: |
          sh -vx
          cd omniscidb
          mkdir -p ${{ env.PREFIX }}
          rm -rf build
          conda info
          conda list -n ${{ env.CONDA_ENV }}
          conda run -n ${{ env.CONDA_ENV }} bash scripts/conda/build-install-all.sh
          cd ..
          tar -zcf /tmp/build.tgz .

      - name: Upload build and src files
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.RUN_STAMP }}-build
          path: /tmp/build.tgz

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.RUN_STAMP }}-logs
          path: |
            omniscidb/build/*.log
            omniscidb/build/CMakeCache.txt 
            omniscidb/build/CMakeFiles/*.log

