name: PyPI manylinux2014_x86_64 deployer
on:
  push:
    #    tags:
    #  - 'v*'
  workflow_dispatch:

jobs:
  # Build and deploy manylinux2014_x86_64 wheels
  # follow numpy schema: https://pypi.org/project/numpy/#files
  Linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v3
        with:
          path: modin
          repository: intel-ai/modin
          ref: ienkovich/pyhdk

      - name: Set environment
        run: |
          mkdir -p build
          touch build/setup.py
          python3 -m pip install --upgrade pip cibuildwheel

      - name: Build manylinux2014_x86_64 wheels
        env:
          CIBW_BEFORE_BUILD: |
            set -vx
            pwd -P 1>&2
            ls 1>&2
            ls /project 1>&2
            cd build
            cmake  .. -DENABLE_CUDA=off -DCMAKE_BUILD_TYPE=release && make -j2 && make install
            pip install wheel cython
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          # cp37 - cp39 are deployed for manylinux2010
          CIBW_BUILD: cp39-*
          CIBW_BUILD_VERBOSITY: 2
        run: |
          cd build
          python -m cibuildwheel --output-dir wheelhouse
          
      - name: Upload manylinux2014_x86_64 wheels to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          ls -l ./wheelhouse
          pip install twine
          twine upload --skip-existing ./wheelhouse/*.whl
