name: Forge
on:
  workflow_dispatch:
    inputs:
      reset-cache:
        type: boolean
        default: true
  schedule:
    - cron: '51 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          path: hdk-feedstock
          repository: conda-forge/hdk-feedstock

      - name: Run build-locally.py
        run: |
          cp recipe/* hdk-feedstock/recipe/
          cd hdk-feedstock
          config=$(cd .ci_support && ls -1 linux*versionNone*python3.9*.yaml)
          python build-locally.py $(basename "$config" .yaml)
