name: Forge
on:
  workflow_dispatch:
    inputs:
      reset-cache:
        type: boolean
        default: true
  schedule:
    - cron: '51 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          path: hdk-feedstock
          repository: conda-forge/hdk-feedstock

      - name: Run build-locally.py
        run: |
          cp recipe/* hdk-feedstock/recipe/
          cd hdk-feedstock
          python build-locally.py linux_64_c_compiler_version9cuda_compilernvcccuda_compiler_version11.0cxx_compiler_version9numpy1.21python3.9.____cpython
