name: CI
on:
  workflow_dispatch:
    inputs:
      reset-cache:
        type: boolean
        default: true
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: '51 2 * * *'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  build-cuda:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      name: cuda
      cuda_compiler_version: 12-0
      options: -DENABLE_CUDA=on

  build-clang:
    name: Build Clang
    uses: ./.github/workflows/build.yml
    with:
      name: clang
      options: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

  build-asan:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      name: asan
      cuda_compiler_version: 12-0
      options: -DENABLE_ASAN=on

  build-l0:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      name: l0
      options: -DENABLE_L0=on

  build-both-l0-cuda:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      name: 'all-gpus'
      cuda_compiler_version: 12-0
      options: -DENABLE_L0=on -DENABLE_CUDA=on

  style:
    name: Style-check
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      cache-suffix: ${{ needs.build.outputs.cache-suffix }}
      test: style

  sanity:
    name: Sanity test (Gtests)
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      cache-suffix: ${{ needs.build.outputs.cache-suffix }}
      test: sanity

  sanity-cpu:
    name: CPU-only Sanity tests (Gtests)
    needs: build-l0
    uses: ./.github/workflows/test.yml
    with:
      name: l0
      cache-suffix: ${{ needs.build.outputs.cache-suffix }}
      test: sanity_cpu
      
  sanity-clang:
    name: Sanity test (Gtests, Clang)
    needs: build-clang
    uses: ./.github/workflows/test.yml
    with:
      name: clang
      cache-suffix: ${{ needs.build.outputs.cache-suffix }}
      test: sanity

  asan:
    name: ASAN generate cache (Gtests)
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      cache-suffix: ${{ needs.build.outputs.cache-suffix }}
      test: asan

  test-asan-docker:
    name: ASAN docker test (Gtests)
    needs: [build-asan, asan]
    uses: ./.github/workflows/test-docker.yml
    with:
      name: conda
      build-name: asan
      reset-cache: ${{ !!inputs.reset-cache }}

  build-cuda-docker:
    name: Build
    uses: ./.github/workflows/build-docker.yml
    with:
      name: cuda
      options: -DENABLE_PYTHON=off -DENABLE_CUDA=on

  build-clang-docker:
    name: Build Clang
    uses: ./.github/workflows/build-docker.yml
    with:
      name: clang
      options: -DENABLE_PYTHON=off -DENABLE_CUDA=on -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

  test-cuda-docker:
    name: Sanity test (Gtests)
    needs: build-cuda-docker
    uses: ./.github/workflows/test-docker.yml
    with:
      name: cuda
      # input for a push event is an empty string, convert it to boolean
      reset-cache: ${{ !!inputs.reset-cache }}

  test-clang-docker:
    name: Sanity test (Gtests)
    needs: build-cuda-docker
    uses: ./.github/workflows/test-docker.yml
    with:
      name: clang
      # input for a push event is an empty string, convert it to boolean
      reset-cache: ${{ !!inputs.reset-cache }}

  build-l0-docker:
    name: Build 
    uses: ./.github/workflows/build-docker.yml
    with:
      name: l0
      options: -DENABLE_L0=on -DENABLE_CUDA=off -DENABLE_PYTHON=off 

  test-l0-docker:
    name: Sanity test (Gtests) 
    needs: build-l0-docker
    uses: ./.github/workflows/test-docker.yml
    with:
      name: l0
      reset-cache: ${{ !!inputs.reset-cache }}
      runner: intel-ai.hdk.l0

  windows-build:
    name: Build
    uses: ./.github/workflows/build-windows.yml
    with:
      name: cpu
      options: -DCMAKE_BUILD_TYPE=Release -DENABLE_FOLLY=off -G "Visual Studio 17 2022"

  windows-sanity:
    name: Sanity test (Gtests)
    needs: windows-build
    uses: ./.github/workflows/test-windows.yml
    with:
      cache-suffix: ${{ needs.windows-build.outputs.cache-suffix }}
      test: sanity

  modin:
    name: Integration HDK with Modin (Pytest)
    uses: ./.github/workflows/modin.yml

  pytest:
    name: PyHDK (Pytest)
    uses: ./.github/workflows/pytest.yml


