name: Build
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV

  push:
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    uses: ./.github/workflows/modin.yml

  build-wheels:
    uses: ./.github/workflows/build-wheels.yml

