name: CI
on:
  workflow_dispatch:
    inputs:
      reset-cache:
        type: boolean
        default: true
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: '51 2 * * *'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  windows-build:
    name: Build on Windows
    uses: ./.github/workflows/windows-build.yml
    with:
      name: release
      options: -DCMAKE_BUILD_TYPE=Release -DENABLE_FOLLY=off -G "Visual Studio 17 2022"

  build-cuda:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      name: cuda
      cuda_compiler_version: 12-0
      options: -DENABLE_CUDA=on

  build-l0:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      name: l0
      options: -DENABLE_L0=on

  build-both-l0-cuda:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      name: 'all-gpus'
      cuda_compiler_version: 12-0
      options: -DENABLE_L0=on -DENABLE_CUDA=on

  style:
    name: Style-check
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      cache-suffix: ${{ needs.build.outputs.cache-suffix }}
      test: style

  sanity:
    name: Sanity test (Gtests)
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      cache-suffix: ${{ needs.build.outputs.cache-suffix }}
      test: sanity

  asan:
    name: Asan test (Gtests)
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      cache-suffix: ${{ needs.build.outputs.cache-suffix }}
      test: asan

#  test-asan-docker:
#    needs: [build-asan, asan]
#    uses: ./.github/workflows/test-docker.yml
#    with:
#      build-name: asan
#      reset-cache: ${{ !!inputs.reset-cache }}


  build-cuda-docker:
    name: Build
    uses: ./.github/workflows/build-docker.yml
    with:
      name: cuda
      options: -DENABLE_PYTHON=off -DENABLE_CUDA=on

  test-cuda-docker:
    name: Sanity test (Gtests)
    needs: build-cuda-docker
    uses: ./.github/workflows/test-docker.yml
    with:
      name: cuda
      # input for a push event is an empty string, convert it to boolean
      reset-cache: ${{ !!inputs.reset-cache }}

  build-l0-docker:
    name: Build 
    uses: ./.github/workflows/build-docker.yml
    with:
      name: l0
      options: -DENABLE_L0=on -DENABLE_CUDA=off -DENABLE_PYTHON=off 

  test-l0-docker:
    name: Sanity test (Gtests) 
    needs: build-l0-docker
    uses: ./.github/workflows/test-l0-docker.yml
    with:
      name: l0
      reset-cache: ${{ !!inputs.reset-cache }}

  modin:
    name: Integration HDK with Modin (Pytest)
    uses: ./.github/workflows/modin.yml

  pytest:
    name: PyHDK (Pytest)
    uses: ./.github/workflows/pytest.yml
