name: Nightly
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  image-build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASS }}
      
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: devjiu/cpu-hdk
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: omniscidb/docker/dev/Dockerfile
          tags: devjiu/cpu-hdk:latest

      - name: Image check
        run:  |
          echo "image_name=hdk-cpu-nightly-$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo ${{ env.image_name }}
          docker image ls -a 

  configuration:
    needs: [image-build]
    uses: ./.github/workflows/main.yml
