name: sanity-tests
on: [ push ]
jobs:
  build:
    runs-on: [ self-hosted, linux, x64 ]
    steps:
      - run: mkdir build && cd build
      - name: cmake
        run: cmake ..
        working-directory: build
      - name: make
        run: make -j 4
        working-directory: build