name: pyhdk tests
on: [ push ]
jobs:
  build:
    runs-on: [ self-hosted, linux, x64 ]
    steps:
      - uses: actions/checkout@v2
      - name: update submodule
        run: |
          git submodule init
          git submodule update
      - run: mkdir build && cd build
      - name: cmake
        run: cmake -DENABLE_PYTHON=on -DBUILD_SHARED_LIBS=on -DENABLE_CONDA=off ..
        working-directory: build
      - name: make
        run: make -j 4
        working-directory: build
      - name: install
        run: make install
        working-directory: build
      - name: tests
        run: pytest
        working-directory: python/tests
