name: Reusable test action on windows
on:
  workflow_call:
    inputs:
      name:
        type: string
        default: "gcc-cpu"
      cache-suffix:
        type: string
        required: true
      test:
        type: string

jobs:
  test:
    name: Test (Win - Conda - ${{ inputs.name }})
    runs-on: windows-latest

    steps:
      - name: Set env context
        run: |
          echo RUN_STAMP=${{ runner.os }}-${{ inputs.name }} >> $env:GITHUB_ENV
          echo CONDA_ENV_PATH=$env:CONDA/envs/omnisci-dev >> $env:GITHUB_ENV

      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.RUN_STAMP }}-win-build

      - name: Unpack build files
        run: |
          Expand-Archive -DestinationPath . build.zip
          dir

      - name: Restore Conda env cache
        id: restore-conda-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ env.CONDA_ENV_PATH }}
          key: ${{ env.RUN_STAMP }}-conda-windows-${{ hashFiles('omniscidb/scripts/mapd-deps-conda-windows-env.yml') }}-${{ env.DATE }}
          restore-keys: |
            ${{ env.RUN_STAMP }}-conda-windows-${{ hashFiles('omniscidb/scripts/mapd-deps-conda-windows-env.yml') }}-

      - name: Run sanity tests
        if: inputs.test == 'sanity'
        run: |
          & $env:CONDA\condabin\conda.bat run --no-capture-output -n omnisci-dev omniscidb/scripts/conda/test.bat
