name: L0 test
on:
  workflow_call:
    inputs:
      name:
        type: string
        default: l0
      reset-cache:
        type: boolean
        default: false

jobs:
  test:
    runs-on: [self-hosted, linux, intel-ai.hdk.l0]
    steps:
      - name: Set env context
        run: |
          echo RUN_STAMP=docker-${{ runner.os }}-${{ inputs.name }} >>$GITHUB_ENV

      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: ${{ env.RUN_STAMP }}-build
    
      - name: Unpack build files
        run: |
          tar -zxf build.tgz

      - name: Build docker image
        run: |
          cat omniscidb/docker/dev/Dockerfile omniscidb/docker/dev/Dockerfile.${{ inputs.name }} >Dockerfile
          docker build . ${{ inputs.reset-cache && '--no-cache' || '' }} --tag hdk-build.${{ inputs.name }}


      - name: Start the container
        run: |
          docker run -id --name hdk-build.${{ inputs.name }} --network host --device --device=/dev/dri:/dev/dri hdk-build.${{ inputs.name }}:latest
          docker exec hdk-build.${{ inputs.name }} mkdir -p /_work/
          docker cp build.tgz hdk-build.${{ inputs.name }}:/_work/
          docker exec hdk-build.${{ inputs.name }} chown -R ghrunner:ghrunner /_work/
          docker exec -u ghrunner hdk-build.${{ inputs.name }} tar -zxf /_work/build.tgz -C /_work/
        
      - name: Test
        run: docker exec -u ghrunner hdk-build.${{ inputs.name }} bash /_work/scripts/conda/intel-gpu-enabling-test.sh

      - name: Stop the container
        if: always()
        run: docker stop hdk-build.${{ inputs.name }} || true
