name: Reusable test action
on:
  workflow_call: 
    inputs:
      name:
        type: string
        default: cpu
      cache-suffix:
        type: string
        required: true
      test:
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set env context
        run: |
          echo RUN_STAMP=${{ runner.os }}-${{ inputs.name }} >>$GITHUB_ENV
          echo CONDA_ENV_PATH=$CONDA/envs/omnisci-dev >>$GITHUB_ENV

      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.RUN_STAMP }}-build

      - name: Unpack build files
        run: |
          tar -zxf build.tgz

      - name: Restore Conda env cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.CONDA_ENV_PATH }}
          key: ${{ env.RUN_STAMP }}-conda-${{ hashFiles('omniscidb/scripts/mapd-deps-conda-dev-env.yml') }}-${{ inputs.cache-suffix }}

      - name: C++ style check
        if: inputs.test == 'style'
        run: |
          conda run --no-capture-output -n omnisci-dev bash -c "find . -name python -prune -or -name build -prune -or -name ThirdParty -prune -or -name third_party -prune -or \( -name '*.cpp' -print -or -name '*.h' -print \) | xargs clang-format --dry-run --Werror -style=file"
        shell: bash

      - name: Py style check
        if: inputs.test == 'style'
        run: |
          eval "$($CONDA/bin/conda shell.bash hook)"
          conda activate omnisci-dev
          find . -type f -name "*.py"  ! -path "./omniscidb/Benchmarks/*" ! -path "./omniscidb/ThirdParty/*" ! -path "./build/*"  ! -path "*version.py" | xargs black --check
        shell: bash

      #	The following tests need more memory than a standard instance has:
      #	  ArrowBasedExecuteTest
      #   ArrowBasedExecuteTestColumnarOutput
      #   ArrowBasedExecuteTestSizeAgnostic
      #   ArrayTest
      #   CorrelatedSubqueryTest
      #   NoCatalogSqlTest
      # that's not possible to manage instance memory with standard actions
      - name: Set Swap Space
        if: inputs.test == 'asan'
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - name: Run sanity tests
        if: inputs.test == 'sanity'
        # skip large buffer tests due to limited memory on ghrunnners instances 
        run: |
          conda run --no-capture-output -n omnisci-dev bash omniscidb/scripts/conda/test.sh -s 

      - name: Run ASAN test
        if: inputs.test == 'asan'

        run: |
          sudo sh -c 'echo 2 >/proc/sys/vm/overcommit_memory'

          cd build/omniscidb/Tests # build cache
          conda run --no-capture-output -n omnisci-dev ./ArrowBasedExecuteTest --build-rel-alg-cache=cache.txt

          tar -zcf /tmp/cache.tgz cache.txt

      - name: Upload build and src files
        if: inputs.test == 'asan'
        uses: actions/upload-artifact@v3
        with:
          name: docker-${{ env.RUN_STAMP }}-asan
          path: /tmp/cache.tgz

